language: node_js
node_js:
  - "0.10"

branches:
  only:
  - master

# install grunt globally
before_install:
  - npm install -g npm@2
  - npm install -g grunt-cli
  - npm install -g bower

# install dev dependencies
install:
  - npm install
  - bower install

before_script:
# remove dist folder from .gitignore file
  - echo 'remove dist folder from .gitignore'
  - sed -i '/dist=/d' .gitignore > .gitignore
  - grunt test
  - grunt build

script:
  # copy dist folder to gh-pages branch
  - ./deploy/scripts/github.sh

  # copy gh-pages branch to phonegap www folder in mobile branch which will trigger apk generation
  - git clone --depth=50 --branch=android https://malteahrens:${GH_TOKEN}@github.com/malteahrens/mvv-app
  - cd mvv-app
  - git show-ref
  - git checkout android
  - ls mvv-app/www
  - pwd
  - git add --all mvv-app/www
  - git config user.name blibla
  - git config user.email blub@github.com
  - git commit . -m "Android App"
  - git config --global push.default simple
  - git push

env:
  global:
    # this is for Travis to be able to push to github to assemble gh-branch
    - secure: "P0SFVXYMJhNb3dX/Hx4rxjL/toViP0Vo0yXbMK/vwOsSrixkU84ltMGykBYTUztdAFJvsO0xrhKsdPbBmdjEF48emrmoymknxKYPIJ6NL1N6fy0EUoE6o7vBX+agthD/uhSNCJgXRK+giqxP5Htz3BkrU9VgdFdVrSqU9bsm4Bc="

