language: node_js
node_js:
- '0.10'
branches:
  only:
#  - master
before_install:
- npm install -g npm@2
- npm install -g grunt-cli
- npm install -g bower
install:
- npm install
- bower install
before_script:
- echo 'remove dist folder from .gitignore'
- sed -i '/dist=/d' .gitignore > .gitignore
- grunt test
- grunt build
script:
- ./deploy/scripts/github.sh
- git clone --depth=50 --branch=android https://malteahrens:${GH_TOKEN}@github.com/malteahrens/mvv-app
- cd mvv-app
- git show-ref
- git checkout android
- rm -R mvv-app/www/*
- ls ../
- cp -R ../dist ./mvv-app/www
- pwd  
- git add --all mvv-app/www
- git config user.name blibla
- git config user.email blub@github.com
- git commit . -m "Android App"
- git config --global push.default simple
- git push
env:
  global:
    secure: "bo+mz1MmYF+AtNdHcBswimI6B9x5TKw4PumUDFK+AQfxZYib5j19Hnb34zsf7TUg0gc6KluP9kHeSg4HeHEuLeqICPFsWdvhHiRKCH+Qjpb+iVBL+FkHRWoceQGezeggt+A/5c68chSdOonWff/gg300XeXCJAS/cKpHCRwur81wNViIVmm4usBYYwCZQhzKftkKlXmMySN+lYudlIH/+BxCmrddpIWA5blvOtB/IMgK6ZyeraPnCbDZlWe0rJYbt6aE5xeBWgJz6UiFbVIqOog9cti6JiFovRtP+VBi3i1KU2ccfFsK1UjzLl/B92SlJE+YGypXyBlI3PeEs8BLDKJ+x9WCj7M/G8vsCD1AHp/haDyx5OsnAzGFeMIp17F6GYBvR4CGdzhRDfe/NuKSQot96PZaaw7+oHAa4MXzItvFKINS7zVaYLasjkTLPfzyauBFYEKySRa8KW573yAc0XBLcQl+klx95SZkCKlu+P22OFG/7wzVOF7m6SWm50V1e7rRy1jc5VGYmMrqX+XrEVmYD66Rr2nsw3dYrRocdwoXXve7dvCBFqCDPldXN31v/qknniAeVherfKbiKwrW+JzQceVuVGj69tKk1KAtu3LbdYZnWOXLWUnRb0/H8IhitsE/d0Ups6IL+XWzoR/hkbIgyvWWab0dFj1KrJD2ZXQ="
