language: android

branches:
  only:
  - android

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools

    # The SDK version used to compile your project
    - android-22

# install npm
before_install:
  - nvm install 0.10
  - npm install phonegap -g

script:
  - phonegap create app com.example.mvv MvvApp
  - cd app
  - phonegap platform add android
  - phonegap plugin add org.apache.cordova.device
  - phonegap plugin add cordova-plugin-vibration
  - phonegap plugin add cordova-plugin-device-orientation
  - phonegap plugin add cordova-plugin-network-information
  - phonegap plugin add cordova-plugin-geolocation
  - phonegap build
  - '/bin/cp -rf platforms/android/build/outputs/apk/*.apk ../release'
  - cd ..

  # copy apk to release folder
  - sh ./deploy/scripts/github.sh

env:
  global:
    # this is for Travis to be able to push back to github
    secure: "bo+mz1MmYF+AtNdHcBswimI6B9x5TKw4PumUDFK+AQfxZYib5j19Hnb34zsf7TUg0gc6KluP9kHeSg4HeHEuLeqICPFsWdvhHiRKCH+Qjpb+iVBL+FkHRWoceQGezeggt+A/5c68chSdOonWff/gg300XeXCJAS/cKpHCRwur81wNViIVmm4usBYYwCZQhzKftkKlXmMySN+lYudlIH/+BxCmrddpIWA5blvOtB/IMgK6ZyeraPnCbDZlWe0rJYbt6aE5xeBWgJz6UiFbVIqOog9cti6JiFovRtP+VBi3i1KU2ccfFsK1UjzLl/B92SlJE+YGypXyBlI3PeEs8BLDKJ+x9WCj7M/G8vsCD1AHp/haDyx5OsnAzGFeMIp17F6GYBvR4CGdzhRDfe/NuKSQot96PZaaw7+oHAa4MXzItvFKINS7zVaYLasjkTLPfzyauBFYEKySRa8KW573yAc0XBLcQl+klx95SZkCKlu+P22OFG/7wzVOF7m6SWm50V1e7rRy1jc5VGYmMrqX+XrEVmYD66Rr2nsw3dYrRocdwoXXve7dvCBFqCDPldXN31v/qknniAeVherfKbiKwrW+JzQceVuVGj69tKk1KAtu3LbdYZnWOXLWUnRb0/H8IhitsE/d0Ups6IL+XWzoR/hkbIgyvWWab0dFj1KrJD2ZXQ="

